[build]
  command = "npm run build"
  publish = ".next"

[template]
  incoming-hooks = ["WixEvents"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[template.environment]
  NEXT_PUBLIC_WIX_CLIENT_ID = process.env.NEXT_PUBLIC_WIX_CLIENT_ID || '',
  WIX_REFRESH_TOKEN = process.env.WIX_REFRESH_TOKEN || '',
